#!/usr/bin/env perl
#
# Default entrypoint script
#

use strict;
use warnings;
use autodie;

## Update the CPAN deps if PDI_UPDATE_DEPS is present
system('/usr/bin/pdi-build-deps') if $ENV{PDI_UPDATE_DEPS};

## Exec the command
exec(@ARGV) if @ARGV;
exec('/bin/sh');
