#!/usr/bin/env perl
#
# Check all Perl scripts under /app/bin and run tests
#

use strict;
use Path::Tiny;

my $app = path('/app');
chdir($app) or exit(0);

for my $folder (qw( bin sbin ), 'lambda-handlers') {
  my $bin = $app->child($folder);
  next unless $bin->is_dir;

  my $bin_it = $bin->iterator;
  while (my $f = $bin_it->()) {
    next unless -x "$f";
    next unless $f->slurp =~ m/^#!.+perl/;

    system($^X, '-I/app/lib', '-wc', "$f") and fatal("Failed to check script '$f'");
  }
}

my $t = $app->child('t');
if ($t->is_dir) {
  my @folders = ($t);
  if (not $t->child('.pdi-run-tests-ok')->is_file) {
    @folders = grep { $_->is_dir and $_->child('.pdi-run-tests-ok')->is_file } $t->children;
  }
  system('prove', '-vr', '-I/app/lib', @folders) and fatal('Failed tests, check them') if @folders;
}

exit(0);


########################
# Utilities

sub fatal {
  print "\n\n***** $@\n\n";
  sleep(2);
  exit(1);
}
